services:
  mysql:
    image: mysql:8.0
    container_name: excel_data_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: excel_data
      MYSQL_USER: excel_user
      MYSQL_PASSWORD: excel_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - excel_network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local

networks:
  excel_network:
    driver: bridge
